### ISSUE TITLE
A simple test with "pi" fails

### ISSUE THREAD

**Issue by monadius** [soarlab/gelpia#16] opened 2016-07-17 05:38 UTC
Code:

    var:
    [0,0] x;

    cost:
    pi * 2;

Result:

    bin/dop_gelpia benchmarks/tests/pi.dop
    ERROR:  An Error has occured
    ERROR:  Return code: 101
    ERROR:  Command used: ['/home/alexey/Work/Projects/gelpia/target/release/cooperative', '-c', '[0]|(pi*[2])', '-f', 'c1', '-i', '', '-x', '0.\
    001', '-y', '0.001', '-r', '0', '-S', 'generated_93d011a102a0', '-n', '', '-t', '0', '-u', '0', '-M', '0', '--seed', '0', '', '']
    ERROR:  Unable to run given executable, does it exist?
    ERROR:  executable: ['/home/alexey/Work/Projects/gelpia/target/release/cooperative', '-c', '[0]|(pi*[2])', '-f', 'c1', '-i', '', '-x', '0.00\
    1', '-y', '0.001', '-r', '0', '-S', 'generated_93d011a102a0', '-n', '', '-t', '0', '-u', '0', '-M', '0', '--seed', '0', '', '']

**Comment by keram88** [comment] 2016-07-17 20:14
This is from Gaol's interval input parser. The problem is "pi" is marked as a point in the parser and gelpia turns 2 into the point interval '[2]'. Gaol's parser doesn't allow intervals after a point (it inexplicably uses two parsers). To see this, 2*pi works. Rather than fix their parser again, we'll translate 'pi' to [3.141592653589793115997963468544185161590576171875, 3.141592653589793560087173318606801331043243408203125]. Gaol round-trips on full decimal expansion, so this won't be an issue.

**Comment by ganeshutah** [comment] 2016-07-17 20:55
good to see these fixes!

**Comment by keram88** [comment] 2016-07-17 21:13
I'm closing this since it's the same issue as https://github.com/soarlab/gelpia/issues/13

**Closed by keram88** 2016-07-17 21:13 UTC
Labels: bug
