### ISSUE TITLE
atan + sqrt bug

### ISSUE THREAD

**Issue by monadius** [soarlab/gelpia#17] opened 2016-07-20 01:59 UTC
Code:

    var:
    [4.0, 6.3504] x1;
    [4.0, 6.3504] x2;

    cost:
    atan(sqrt((x1 - 5) * (x2 - 5) * (x1 + x2 - x2 - 5) * (x2 - 5)));

Result:

    bin/dop_gelpia benchmarks/tests/atan_bug.dop
    [[1.536809325000001, 1.109576699561335], {'x2': [6.0566, 6.350400000000001], 'x1': [6.2035, 6.350400000000001]}]
    Parsing time: 0.0034666061401367188
    Solver time: 0.10190701484680176

The result should be a valid interval (lower_bound <= upper_bound) which is not true for this example: 1.5368... > 1.1095...

It seems that the lower bound is computed for atan(x) where x is a large number (because atan(+infinity) = pi / 2 = 1.57...)

**Comment by monadius** [comment] 2016-07-20 02:14
Another bug with atan and sqrt:

    var:
    [4.0, 6.3504] x1;
    [4.0, 6.3504] x2;
    [4.0, 6.3504] x3;
    [4.0, 6.3504] x4;
    [4.0, 6.3504] x5;
    [4.0, 6.3504] x6;

    cost:
    atan(x2*x3 / sqrt(4 * x1));

Result:

    bin/dop_gelpia benchmarks/tests/atan_bug2.dop
    [E0425]/home/alexey/Work/Projects/gelpia/src/func/src/lib_generated_f07bd4f0fd98.rs:7     atan(((_x[1]*_x[2])/sqrt((_c[0]\
    *_x[0]))))^~~~/home/alexey/Work/Projects/gelpia/src/func/src/lib_generated_f07bd4f0fd98.rs:7:5: 7:9 help: run `rustc --ex\
    plain E0425` to see a detailed explanationerror: aborting due to previous error', src/function/src/lib.rs:188note: Run wi\
    th `RUST_BACKTRACE=1` for a backtrace.[[1.471904571153197,1.471931994344534], {'x1' : [4, 4.073450000000001],'x2' : [6.20\
    35, 6.350400000000001],'x3' : [6.2035, 6.350400000000001],'x4' : [4.440699999999999, 4.587600000000001],'x5' : [4, 4.1469\
    00000000001],'x6' : [4.2938, 4.4407],}]

Note that everything works if extra variables (x4, x5, x6) are removed.

**Comment by IanBriggs** [comment] 2016-07-20 22:27
Mark, if the expression (first atan problem) is ran through gaol-repl with the given answer put in for x1 and x2 the result is [0.83549..., 1.10957...]

(The expression given to gaol-repl)
atan(sqrt((((([6.2035, 6.350400000000001]-[5])*([6.0566, 6.350400000000001]-[5]))*((([6.2035, 6.350400000000001]+[6.0566, 6.350400000000001])-[6.0566, 6.350400000000001])-[5]))*([6.0566, 6.350400000000001]-[5]))))

**Comment by IanBriggs** [comment] 2016-07-20 22:30
I am unable to reproduce the second atan problem.

`[[1.471904571153197, 1.471931994344534], {'x2': [6.2035, 6.350400000000001], 'x6': [4.2938, 4.4407], 'x3': [6.2035, 6.350400000000001], 'x5': [4, 4.146900000000001], 'x1': [4, 4.073450000000001], 'x4': [4.440699999999999, 4.587600000000001]}]
Parsing time: 0.004042148590087891
Solver time: 10.216643810272217`


Though this does remind me of a needed improvement of not using unused variables in the search space (will open a ticket for that)

**Comment by IanBriggs** [comment] 2016-07-20 23:15
Mark, the wrong value is coming from est_func.

**Comment by keram88** [comment] 2016-07-21 01:16
Closing this since the root cause is the same as https://github.com/soarlab/gelpia/issues/15.

**Closed by keram88** 2016-07-21 01:16 UTC
Labels: bug
